Changing it up so it clones, rather than uses your current state.

diff --git a/release/release b/release/release
--- a/release/release
+++ b/release/release
@@ -11,16 +11,67 @@ command -v git > /dev/null 2>&1 || die "git is not installed. Bailing!"
 command -v go > /dev/null 2>&1 || die "go is not installed. Bailing!"
 command -v virtualenv > /dev/null 2>&1 || die "virtualenv is not installed. Bailing!"
 
+BUILD_PLATFORMS=(linux_amd64 windows_amd64)
+GIT_COMMIT_ID=$1
+GIT_REPO_NAME=tzsebe/release-experimentation
 API_TOKEN_FILE=$HOME/.github-release-api-token
 RELEASE_VIRTUALENV_DIR=$HOME/virtual-envs/tzsebe-releaser
-BUILD_DIR=$(go env GOPATH)/src/github.com/tzsebe/release-experimentation
-RELEASE_DIR=$BUILD_DIR/release
-OUTPUT_DIR=$RELEASE_DIR/output
+SOURCE_DIR=$(go env GOPATH)/src/github.com/tzsebe/release-experimentation
+RELEASE_DIR=$SOURCE_DIR/release
+WORKING_DIR=$RELEASE_DIR/tmp-release-ephemeral
+REPO_DIR=$WORKING_DIR/repo
+ARTIFACT_DIR=$WORKING_DIR/build_artifacts
+MAIN_SOURCE=hello/hello.go
+BINARY_NAME=hello
+BINARY_PATH=$BINARY_NAME/bin
+ASSET_DIR=$WORKING_DIR/assets
 
-[[ -d $BUILD_DIR ]] || die "Directory $BUILD_DIR does not exist."
+
+[[ -d $SOURCE_DIR ]] || die "Directory $SOURCE_DIR does not exist."
 [[ -d $RELEASE_DIR ]] || die "Directory $RELEASE_DIR does not exist."
 [[ -f $API_TOKEN_FILE ]] || die "File $API_TOKEN_FILE does not exist."
 [[ $(stat --format '%a' $API_TOKEN_FILE) == "400" ]] || die "File $API_TOKEN_FILE must have mode '400'"
+[[ $GIT_COMMIT_ID =~ ^[0-9a-f]{40}$ ]] || die "First argument should be git commit ID."
+
+# Clean up any old release work, and start fresh.
+echo "Retrieving code to release..."
+rm -rf $WORKING_DIR
+mkdir -p $REPO_DIR
+pushd $REPO_DIR > /dev/null
+git clone git@github.com:$GIT_REPO_NAME.git .
+git checkout $GIT_COMMIT_ID
+echo "Done retrieving code."
+echo ""
+
+# Run tests - Never allow releases that fail unit tests.
+echo "Running unit tests..."
+go test ./... || die "\nUnit tests are failing. Not allowing release to proceed."
+echo "Done running tests."
+echo ""
+
+# Build for every OS/Arch combination we support.
+echo "Building release assets..."
+mkdir -p $ASSET_DIR
+for os_arch in ${BUILD_PLATFORMS[@]}; do
+  build_os=$(echo $os_arch | cut -f1 -d_)
+  build_arch=$(echo $os_arch | cut -f2 -d_)
+  echo "Building for $build_os/$build_arch..."
+  mkdir -p $ARTIFACT_DIR/$os_arch
+
+  if [[ $build_os == "windows" ]]; then
+    GOOS=$build_os GOARCH=$build_arch go build -o $ARTIFACT_DIR/$os_arch/$BINARY_PATH/$BINARY_NAME.exe $MAIN_SOURCE
+    pushd $ARTIFACT_DIR/$os_arch > /dev/null
+    zip -r -q $ASSET_DIR/$BINARY_NAME-$os_arch.zip $BINARY_NAME > /dev/null
+    popd > /dev/null
+  else
+    GOOS=$build_os GOARCH=$build_arch go build -o $ARTIFACT_DIR/$os_arch/$BINARY_PATH/$BINARY_NAME $MAIN_SOURCE
+    tar -czf $ASSET_DIR/$BINARY_NAME-$os_arch.tar.gz -C $ARTIFACT_DIR/$os_arch $BINARY_NAME
+  fi
+done
+popd > /dev/null
+
+echo "Done building."
+echo ""
 
 # If the virtual environment doesn't exist, create it.
 if [[ ! -d $RELEASE_VIRTUALENV_DIR ]]; then
@@ -29,53 +80,16 @@ if [[ ! -d $RELEASE_VIRTUALENV_DIR ]]; then
   virtualenv $RELEASE_VIRTUALENV_DIR
 fi
 
+# Install dependencies and run our actual release creation.
 (
-  # Start up the virtual environment and install all necessary packages.
   source $RELEASE_VIRTUALENV_DIR/bin/activate
   [[ ! -z $VIRTUAL_ENV ]] || die "Failed to activate virtual environment!"
-  echo "Activated virtual environment: $VIRTUAL_ENV"
-  cd $BUILD_DIR
-  pip install -r release/requirements.txt
+  echo "Checking for dependencies in environment $VIRTUAL_ENV"
+  cd $RELEASE_DIR
+  pip install -r requirements.txt
   echo "Done with setup."
-
-  # If your tests fail, YOU fail. :)
-  echo "Running unit tests."
-  go test ./... || die "\nUnit tests are failing. Not allowing release to proceed."
-  echo "Done running tests."
-
-  # Run all the builds
-  echo "Creating builds..."
-  rm -rf $OUTPUT_DIR
-  for os_arch in "linux_amd64" "windows_amd64"; do
-    build_os=$(echo $os_arch | cut -f1 -d_)
-    build_arch=$(echo $os_arch | cut -f2 -d_)
-    echo "Building for OS $build_os, ARCH $build_arch..."
-    mkdir -p $OUTPUT_DIR/$os_arch
-
-    if [[ $build_os == "windows" ]]; then
-      echo "  build..."
-      GOOS=$build_os GOARCH=$build_arch go build -o $OUTPUT_DIR/$os_arch/hello/hello.exe hello/hello.go
-      echo "  compress..."
-      pushd $OUTPUT_DIR/$os_arch
-      zip -r -q ../hello-$os_arch.zip hello
-      popd
-    else
-      echo "  build..."
-      GOOS=$build_os GOARCH=$build_arch go build -o $OUTPUT_DIR/$os_arch/hello/hello hello/hello.go
-      echo "  compress..."
-      tar -czf $OUTPUT_DIR/hello-$os_arch.tar.gz -C $OUTPUT_DIR/$os_arch hello/hello
-    fi
-    echo "  cleanup..."
-    rm -rf $OUTPUT_DIR/$os_arch
-  done
-
-  # Get current state and pass it along.
-  LATEST_COMMIT=$(git log | head -n1 | cut -d ' ' -f2)
-  CURRENT_BRANCH=$(git branch | grep '^*' | head -n1 | cut -c 3-)
-  [[ ! -z $LATEST_COMMIT ]] || die "Failed to retrieve latest git commit!"
-  [[ ! -z $CURRENT_BRANCH ]] || die "Failed to retrieve current branch!"
-  echo "Current commit: [$CURRENT_BRANCH]@[$LATEST_COMMIT]"
-  API_TOKEN_FILE=$API_TOKEN_FILE SNAPSHOT_COMMIT=$LATEST_COMMIT SNAPSHOT_BRANCH=$CURRENT_BRANCH ASSET_DIR=$OUTPUT_DIR python release/release.py
+  echo ""
+  python release.py $API_TOKEN_FILE $GIT_REPO_NAME $GIT_COMMIT_ID $ASSET_DIR
 )
 
 echo "Done!"
